### ISSUE TITLE
JsonReaderException: ',' is an invalid start of a property name. Expected a '"'. LineNumber: 11 |

### ISSUE THREAD

**Issue by Yoshuwa** [ExesoftInc/TenantAPI#1]
I'm reporting this issue:

`JsonReaderException: ',' is an invalid start of a property name. Expected a '"'. LineNumber: 11 | BytePositionInLine: 2.
System.Text.Json.ThrowHelper.ThrowJsonReaderException(ref Utf8JsonReader json, ExceptionResource resource, byte nextByte, ReadOnlySpan<byte> bytes)

FormatException: Could not parse the JSON file.`

**Comment by George-GEHC** [comment]
There was an extra comma in the appsettings. Thanks for raising the issue
